apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vinver1981/argocd.git
    targetRevision: main  # Branch, tag, or commit SHA to deploy
    path: /  # Optional: path within the repo where the manifests are located
  #project: default  # Argo CD project name
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

