apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-first-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  #Folling line will configure aws loadbalancer the URL will run without using ports
  #ports:
  #  - protocol: TCP
  #    port: 80
  #    targetPort: 8080
  #type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-pod
  template:
    metadata:
      labels:
        app: my-first-pod
    spec:
      containers:
      - name: node-application 
        image: vinver1981/k8-first-app:2
        ports:
        - containerPort: 8080